# Generated by Django 2.0.7 on 2019-04-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighttracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
