# Generated by Django 2.0.7 on 2019-04-16 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Others', max_length=10)),
                ('my_goal', models.CharField(choices=[('LF', 'Lose Fat'), ('GM', 'Gain Muscle'), ('TF', 'Transform')], default='TF', max_length=2)),
                ('activity', models.CharField(choices=[('VA', 'Very Active'), ('AC', 'Active'), ('NA', ' Not Active')], default='AC', max_length=2)),
                ('height', models.IntegerField(blank=True)),
                ('age', models.IntegerField(blank=True)),
                ('weight', models.IntegerField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
