# Generated by Django 2.0.7 on 2019-04-16 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodtable', '0002_auto_20190416_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtable.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
                ('foods', models.ManyToManyField(through='dietplan.GeneratedBy', to='foodtable.Food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='generatedby',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietplan.Plan'),
        ),
    ]
