# Generated by Django 2.0.7 on 2019-04-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11, unique=True)),
                ('carbs', models.IntegerField()),
                ('fiber', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('source_type', models.CharField(max_length=15)),
            ],
        ),
    ]
