# Generated by Django 2.0.7 on 2019-04-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='source_type',
            field=models.CharField(choices=[('pt', 'Main Protein Source'), ('ft', 'Main Fat Source'), ('ct', 'Main Carbonhydrate Source')], default='ct', max_length=2),
        ),
    ]
